# Fine‑tune SimAM‑ResNet34 pretrained on VoxBlink2 (large‑margin stage)
# -------------------------------------------------------------------
# This file is adapted from resnet_lm.yaml to fine‑tune a VoxBlink2
# pretrained model on a custom dataset.

# -------------------------------------------------------------------
# Experiment & hardware
# -------------------------------------------------------------------
exp_dir: exp/samresnet34_voxblink_ft22

gpus: [1]          # match torchrun and CUDA_VISIBLE_DEVICES
num_avg: 1
enable_amp: false

do_lm: true
seed: 42
num_epochs: 6
save_epoch_interval: 1
log_batch_interval: 100

# -------------------------------------------------------------------
# Data loader
# -------------------------------------------------------------------
data_type: shard

dataloader_args:
  batch_size: 24
  num_workers: 16
  pin_memory: false
  prefetch_factor: 8
  drop_last: true

# -------------------------------------------------------------------
# Dataset
# -------------------------------------------------------------------
dataset_args:
  sample_num_per_epoch: 0
  shuffle: true
  shuffle_args:
    shuffle_size: 2500
  filter: true
  filter_args:
    min_num_frames: 200
    max_num_frames: 800
  resample_rate: 16000
  speed_perturb: false  # disable SP for fine-tuning
  num_frms: 600
  aug_prob: 0.3          # lighter augmentation for fine-tune
  fbank_args:
    num_mel_bins: 80
    frame_shift: 10
    frame_length: 25
    dither: 1.0
  spec_aug: false
  spec_aug_args:
    num_t_mask: 1
    num_f_mask: 1
    max_t: 10
    max_f: 8
    prob: 0.6

# -------------------------------------------------------------------
# Model - must match VoxBlink2 pretraining
# -------------------------------------------------------------------
model: SimAM_ResNet34_ASP
model_init: /local/scratch/arfarh/wespeaker/wespeaker/examples/voxceleb/v2/voxblink2/voxblink2_samresnet34_ft/avg_model.pt
model_args:
  embed_dim: 256

# -------------------------------------------------------------------
# Projection and margin schedule
# -------------------------------------------------------------------
projection_args:
  project_type: arc_margin
  scale: 32.0
  easy_margin: false

margin_scheduler: MarginScheduler
margin_update:
  initial_margin: 0.0
  final_margin: 0.3
  increase_start_epoch: 0
  fix_start_epoch: 3
  update_margin: true
  increase_type: linear
  epoch_iter: 4265

# -------------------------------------------------------------------
# Loss and optimization
# -------------------------------------------------------------------
loss: CrossEntropyLoss
loss_args: {}

optimizer: SGD
optimizer_args:
  momentum: 0.9
  nesterov: true
  weight_decay: 0.0001

scheduler: ExponentialDecrease
scheduler_args:
  initial_lr: 5.0e-5
  final_lr: 1.0e-5
  warm_up_epoch: 0
  warm_from_zero: false

